version: '1.0.1'

services:
  react-app:
    build:
      context: .  
      dockerfile: Dockerfile
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_BASE_URL_ACCESS_CONTROL=${VITE_BASE_URL_ACCESS_CONTROL}
    ports:
      - "80:80"
    container_name: react-front-api
    restart: always
